- name: Install unzip and curl
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download NATS CLI .deb package
  get_url:
    url: "https://github.com/nats-io/natscli/releases/download/v0.2.3/nats-0.2.3-amd64.deb"
    dest: "/tmp/natscli.deb"

- name: Install NATS CLI .deb package
  apt:
    deb: "/tmp/natscli.deb"

- name: Create subscriber script
  copy:
    dest: /usr/local/bin/nats-sub.sh
    mode: '0755'
    content: |
      #!/bin/bash
      nats pub updates "Hello from publisher!" -s nats://admin:123@{{ nats_server_ip }}:4222


- name: Run subscriber script as background service
  shell: nohup /usr/local/bin/nats-sub.sh > /var/log/nats-subscriber.log 2>&1 &